#!/usr/bin/env bash
dir=$(fd -H --type d --type l --max-depth=1 -u --search-path ~ --search-path ~/personal --search-path ~/work --search-path ~/fhnw --search-path ~/sourcecode --search-path ~/.config | fzf-tmux -p)

cd $dir
