#!/usr/bin/env bash

session=$(find ~/ ~/work ~/work/temp ~/personal ~/personal/temp ~/fhnw ~/fhnw/algd1 ~/sourcecode ~/.config -mindepth 1 -maxdepth 1 -type d,l | fzf-tmux -p)
session_name=$(basename "$session" | tr . _)

if ! tmux has-session -t "$session_name" 2> /dev/null; then
    tmux new-session -s "$session_name" -c "$session" -d
fi

tmux switch-client -t "$session_name"

